[features]
seeds = false
skip-lint = false
[programs.devnet]
sym_prices_v2 = "heD5N6R8z9TgJJHrDJtnPwj9EsZvrYtHFbxhFjyjb1p"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/macintoshhd/my-solana-wallet/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
